### ISSUE TITLE
Choosing satellites to work with

### ISSUE THREAD

**Issue by bjorgan** [la1k/flyby#20]
If we end up with a system-wide TLE database (issue #1), or add support for multiple TLE files, or even now when the single TLE file becomes large and cumbersome to edit, it might be nice to be able to mark in a checklist which TLEs we want to display in MultiView() and be able to track in SingleTrack() and Predict(). 

E.g. 

[  ] AAUSAT
[X] NOAA-15
[  ] NOAA-17

, in a separate view. Will require a new config file, however. A blacklist over TLEs not to display, where the default option is to not have the file at all, and thus show all satellites. 

Can be implemented in practice by having the full list of TLE-strings available within the program, and let the array over predict_orbit_t be restricted to TLEs not contained within the blacklist. 

Search functionality might be nice. Might also be nice to have the option to sort the checklist into the files they come from and deselect entire TLE-files.

**Comment by ryeng** [comment]
It also makes sense to whitelist a subset of satellites, e.g., only show GPS satellites.

Pattern matching is also an option.

**Comment by bjorgan** [comment]
Fixed in cac6bb05a60e5b8a64b96062c5511a3f7c36e552
