### ISSUE TITLE
Pass quality data in single track.

### ISSUE THREAD

**Issue by oyvkar** [la1k/flyby#46]
A common way to estimate the quality of a satellite pass is by the maximum elevation angle. 
For a LEO satellite the path loss is the lowest when the satellite passes over zenith (90 deg), the distance between ground station and satellite typically varies between 2000 to 4000 km at 0 degree elevation and 300 to 600 km (orbit height) at 90 degree. At zenith it is also likely to be the least obstructed by vegetation and buildings.

It would be nice to see the maximum elevation and the angle and time at which it occurs in single track mode. It would also be nice to see when and at what angle AOS and LOS occur.

![azel_info](https://cloud.githubusercontent.com/assets/10960096/23708801/821c2e16-0417-11e7-8880-ee7df875af6d.png)

**Comment by bjorgan** [comment]
Fixed in b5ebc0dc617f9425c63b8bbfc7ab68001f8be677
