### ISSUE TITLE
Show max elevation angle in multitrack. 

### ISSUE THREAD

**Issue by oyvkar** [la1k/flyby#47]
A common way to estimate the quality of a satellite pass is by the maximum elevation angle.
For a LEO satellite the path loss is the lowest when the satellite passes over zenith (90 deg), the distance between ground station and satellite typically varies between 2000 to 4000 km at 0 degree elevation and 300 to 600 km (orbit height) at 90 degree. At zenith it is also likely to be the least obstructed by vegetation and buildings.

Getting data from satellites is much easier with a "good pass", ie. high elevation angles (30-90 degrees), than with a "bad pass" (5-10 degrees).

For this reason the maximum elevation of a pass should be displayed in multitrack.

**Comment by bjorgan** [comment]
Fixed in 0726d1e1bf964d9feacf29de7935ebbabd6aedf0
