### ISSUE TITLE
Hotkey for move to AOS position

### ISSUE THREAD

**Issue by core-dd** [la1k/flyby#71]
Started using flyby now for some satellite passes. :) Would be really useful to have a hotkey for moving the antenna to the AOS position before the pass starts, might find the time at some point to build a PR, hence the issue is basically a reminder.

**Comment by bjorgan** [comment]
I went ahead and fixed this in 8a3ad4da8f1be01eb6ec76e2c3d77f83e9b64342 while I in any case was fiddling in the same area of the code. Will move to AOS position on 'A' keypress.
