### ISSUE TITLE
QTH locator entry

### ISSUE THREAD

**Issue by bostrt** [la1k/flyby#72]
First time flyby user here. When I was initially setting up my QTH locator (FM05OS), I just typed in FM05 (out of habit) since that is all I would normally provide when making a contact via satellite. After saving the data in the QTH for, it changed to EM83pp!

I understand that having as fine a locator as possible is necessary for flyby to provide accurate data. But I guess I would have expected flyby to keep my FM05 setting and then maybe remind me about being more  specific with my locator entry?

**Comment by bjorgan** [comment]
Thanks for the issue! :-) There were a couple of problems in the locator conversion code and handling of the input buffer from the input field, which should now be fixed after bfad536e22e4c0789ad18c8fed011070a54db70a. Added a notice for shorter locator lengths.
