### ISSUE TITLE
Tracking of Solar System Objects - UI

### ISSUE THREAD

**Issue by core-dd** [la1k/flyby#82]
Exposing tracking features of https://github.com/la1k/libpredict/issues/83 to the user.

**Comment by bjorgan** [comment]
IIiiiiiiiiiii started fiddling with an interface for this this during the weekend, it currently has working tracking of the sun and the moon. I have pushed it to https://github.com/la1k/flyby/tree/issue82-track-sunmoon.

**Comment by bjorgan** [comment]
Added interface in 753cc8223c587fdaee142b0974f98c8372017428. Closing this for now, we can open new issues once more astronomical objects are added in https://github.com/la1k/libpredict/issues/83.
